name: contatos_app
description: Aplicativo de gerenciamento de contatos - Projeto II
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Ícones adicionados em assets/icons/ — mantido descomentado conforme solicitado
  assets:
    - assets/icons/
